FROM alpine
RUN apk add --update --no-cache alpine-sdk bash python curl
WORKDIR /root
RUN git clone https://github.com/edenhill/librdkafka.git
WORKDIR /root/librdkafka
RUN /root/librdkafka/configure
RUN make
RUN make install \
&& apk add nginx
#For golang applications RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2
RUN sudo mkdir /run/nginx
EXPOSE 80
CMD nginx -g 'daemon off;'
#ENTRYPOINT ["/bin/bash"]


