version: "2"
services:
  zookeeper:
    image: confluent/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
#    network_mode: "host"
  broker:
    image: confluent/kafka
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
#    network_mode: "host"
    volumes:
      - $PWD/kafka-logs:/var/log/kafka
  rest-proxy:
    hostname: rest-proxy
    container_name: rest-proxy
    image: confluent/rest-proxy
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "8082:8082"
    environment:
      RP_ZOOKEEPER_CONNECT: "zookeeper:2181"
      RP_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
#    network_mode: "host"
  schema-registry:
    hostname: schema-registry
    container_name: schema-registry
    image: confluent/schema-registry
    depends_on:
      - broker
      - zookeeper
    ports:
      - "8081:8081"
    environment:
      SR_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
#    network_mode: "host"
  nginx-librdkafka1:
    hostname: nginx-librdkafka1
    container_name: nginx-librdkafka1
    image: nginx-librdkafka
    depends_on:
      - zookeeper
      - broker
      - schema-registry
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
#    network_mode: "host"
